// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd-REaG9u4CznYn3VO0uo22rwsgpNq57Q',
    appId: '1:448535141932:web:5a0e1892d04142a9a23b89',
    messagingSenderId: '448535141932',
    projectId: 'rakshak-app-4c332',
    authDomain: 'rakshak-app-4c332.firebaseapp.com',
    storageBucket: 'rakshak-app-4c332.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS4aXOoWxn_yLAl_WeH8ibcsjw7AZyu4k',
    appId: '1:448535141932:android:1044a6604b4a0069a23b89',
    messagingSenderId: '448535141932',
    projectId: 'rakshak-app-4c332',
    storageBucket: 'rakshak-app-4c332.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRvnXGdXN2M6kQFk_w4bVD2aCwyL-txHw',
    appId: '1:448535141932:ios:7c02e524ff5bae73a23b89',
    messagingSenderId: '448535141932',
    projectId: 'rakshak-app-4c332',
    storageBucket: 'rakshak-app-4c332.appspot.com',
    iosBundleId: 'com.example.rakshakApp',
  );
}
